language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra
    # SDK Version to compile project
    - android-25
    - android-21
        
script: ./gradlew build

deploy:
  provider: releases
  api_key:
    secure: "edfe2a84922e51bd9f23abde335126454d1f9841"
  file: "app/build/outputs/apk/app*release*.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: trongvu/ATCommander
